Project/DEBTALMIS/DENTALMIS.Web/Models/ClinicDescriptionModel/ClinicAccessoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DENTALMIS.Model;

namespace DENTALMIS.Web.Models.ClinicDescriptionModel
{
    public class ClinicAccessoryViewModel :ClinicalAccessory
    {

        public List<ClinicalAccessory> ClinicalAccessories { get; set; }

        public string SearchbyName { get; set; }

        public ClinicAccessoryViewModel()
        {
            ClinicalAccessories=new List<ClinicalAccessory>();
        }
    }
}

Project/DEBTALMIS/DENTALMIS.Web/Controllers/ClinicAccessoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DENTALMIS.BLL.Manager.ClinicSectionManager;
using DENTALMIS.Model;
using DENTALMIS.Web.Models.ClinicDescriptionModel;

namespace DENTALMIS.Web.Controllers
{
    public class ClinicAccessoriesController : BaseController
    {
        //
        // GET: /ClinicAccessories/
        public ActionResult Index(ClinicAccessoryViewModel model)
        {
            ModelState.Clear();
            var totalrecords = 0;
            model.Name = model.SearchbyName;

           
            model.ClinicalAccessories = ClinicAccessoryManager.GetAllAccessoriesByPaging(out totalrecords, model);



            model.TotalRecords = totalrecords;

            return View(model);

        }



        public ActionResult Edit(ClinicAccessoryViewModel model)
        {
           
            if (model.AccessoriesId > 0)
            {
                ClinicalAccessory clAssc = ClinicAccessoryManager.GetAccessoriesById(model.AccessoriesId);

                model.AccessoriesId = clAssc.AccessoriesId;
                model.Name = clAssc.Name;
                model.Purpose = clAssc.Purpose;
                model.StockAmount = clAssc.StockAmount;
                model.MarketCost = clAssc.MarketCost;




            }

            return View(model);
        }

        public JsonResult Save(ClinicAccessoryViewModel model)
        {
            int saveIndex = 0;

            ClinicalAccessory clinicalAccessory = new ClinicalAccessory();

            clinicalAccessory.AccessoriesId = model.AccessoriesId;
            clinicalAccessory.Name = model.Name;
            clinicalAccessory.Purpose = model.Purpose;
            clinicalAccessory.MarketCost = model.MarketCost;
            clinicalAccessory.StockAmount = model.StockAmount;




            saveIndex = model.AccessoriesId == 0 ? ClinicAccessoryManager.Save(clinicalAccessory) : ClinicAccessoryManager.Edit(clinicalAccessory);


            return Reload(saveIndex);
        }
        public JsonResult Delete(ClinicAccessoryViewModel model)
        {
            int deleteIndex = 0;
            try
            {
                deleteIndex = ClinicAccessoryManager.Delete(model.AccessoriesId);
            }
            catch (Exception exception)
            {

                throw new Exception(exception.Message);
            }
            return deleteIndex > 0 ? Reload() : ErroResult("Failed To Delete");
        }
	}
}
	

Project/DEBTALMIS/DENTALMIS.Web/Views/ClinicAccessories/Edit.cshtml
@using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder
@using DENTALMIS.Web.Extension
@model  DENTALMIS.Web.Models.ClinicDescriptionModel.ClinicAccessoryViewModel
@{
    ViewBag.Title = (Model.AccessoriesId > 0) ? "Edit" : "Save";
    Layout = "~/Views/Shared/_Layout.Dialog.cshtml";

}
@using (Html.BeginForm("Save", "ClinicAccessories", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.AccessoriesId)

    <table>
        <tr class="form_group">
            <td>
                @Html.LabelFor(x => x.Name)
                @Html.EditorFor(x => x.Name, new { htmlAttributes = new { @class = "text ui-widget-content ui-corner-all" } })

                @Html.ValidationMessageFor(x => x.Name)
            </td>
            <td></td>
            <td></td>

            <td></td>

            <td></td>

            <td></td>


            <td>
                @Html.LabelFor(x => x.Purpose)
                @Html.EditorFor(x => x.Purpose, new { htmlAttributes = new { @class = "text ui-widget-content ui-corner-all" } })

                @Html.ValidationMessageFor(x => x.Purpose)
            </td>



        </tr>
        <tr class="form_group">





            <td>
                @Html.Label("Market Price")
                @Html.EditorFor(x => x.MarketCost, new { htmlAttributes = new { @class = "text ui-widget-content ui-corner-all" } })

                @Html.ValidationMessageFor(x => x.MarketCost)
            </td>
            <td></td>
            <td></td>

            <td></td>

            <td></td>

            <td></td>
            <td>
                @Html.Label("Stok Ammount")
                @Html.EditorFor(x => x.StockAmount, new { htmlAttributes = new { @class = "text ui-widget-content ui-corner-all" } })

                @Html.ValidationMessageFor(x => x.StockAmount)
            </td>


            



        </tr>

        <tr class="form_group">
            <td style="float: left">
                @Html.SaveButton()
            </td>
        </tr>


    </table>
}

Project/DEBTALMIS/DENTALMIS.Web/Views/ClinicAccessories/Index.cshtml
@using DENTALMIS.Utility
@using DENTALMIS.Web.Extension
@model DENTALMIS.Web.Models.ClinicDescriptionModel.ClinicAccessoryViewModel
@{
    ViewBag.Title = "Clinic Accessoriess";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 style="margin-left: 450px; font-weight: bolder;color: darkblue;">[--Clinic Accesssories--]</h3>
<section class="search formCover" style="margin-bottom: 5px;">
    @using (Html.BeginForm("Index", "ClinicAccessories", FormMethod.Get, new { @class = "submit-allow ignore-validation" }))
    {
        <table>
            <tr>
                <td>
                    <strong>
                        @Html.LabelFor(x => x.Name)

                    </strong>
                </td>
                <td></td>
                <td></td>

                <td>@Html.TextBoxFor(x => x.SearchbyName, new { @placeholder = "Search", @class = "search_TextBox" })</td>

                <td></td>




                <td>@Html.SearchButton()</td>
            </tr>
        </table>
    }
</section>


<section class="search formCover">
    <div class="additem">
        <div style="margin-top: 1px;">
            <p>@Html.Button("Add new", new { @class = "AjaxPopup", @action = "/ClinicAccessories/Edit/" })</p>
        </div>
        @{
            var grid = new WebGrid(canPage: true, rowsPerPage: AppConfig.PageSize, canSort: true, ajaxUpdateContainerId: "grid");
            grid.Bind(Model.ClinicalAccessories, rowCount: Model.TotalRecords, autoSortAndPage: false);
            grid.Pager(WebGridPagerModes.All);
            @grid.GetHtml(htmlAttributes: new { id = "grid" },
            tableStyle: "webgrid-table webgrid",
            headerStyle: "webgrid-header",
            footerStyle: "webgrid-footer",
            alternatingRowStyle: "webgrid-alternating-row",
            selectedRowStyle: "webgrid-selected-row",
            rowStyle: "webgrid-row-style",
            firstText: "First",
            lastText: "last",
            nextText: "Next",
            mode: WebGridPagerModes.All,
            previousText: "Previous",
            columns: grid.Columns(
                              grid.Column("Name", header: "Clinic Intrumeent Name"),

                                                                                                               grid.Column("Purpose", header: "Accesssory Purpose"),




                                                                                                      grid.Column("MarketCost", header: "Market Price In Taka", format: @<text>@(item.MarketCost == null ? "" : item.MarketCost.ToString())</text>),
                                                                                                                                                                                                                      grid.Column("StockAmount", header: "Stock Amount", format: @<text>@(item.StockAmount == null ? "" : item.StockAmount.ToString())</text>),


                grid.Column("Detail/Edit", format: @<text><button class="edit" action="/ClinicAccessories/Edit/?AccessoriesId=@item.AccessoriesId"></button></text>, canSort: false),
                         grid.Column("Delete",format:@<text><button class="delete" action="/ClinicAccessories/Delete/?AccessoriesId=@item.AccessoriesId"></button></text>, canSort: false)));



        }
    </div>
</section>