Project/DEBTALMIS/DENTALMIS.Web/Models/DiseasesSectionViewModel/DiseasesManagementViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DENTALMIS.Model;

namespace DENTALMIS.Web.Models.DiseasesSectionViewModel
{
    public class DiseasesManagementViewModel :DiseasesManagement
    {
        public List<DiseasesManagement> DiseasesManagements { get; set; }
        public List<DisesesClinicalFeature> DisesesClinicalFeatures { get; set; }
        public List<DiseasesInvestigation> DiseasesInvestigations { get; set; }

        public List<Disease> DiseasesList { get; set; }

        public string SearchByDiseasesName { get; set; }
        public string SearchByManagementName { get; set; }


        public IEnumerable<SelectListItem> DiseaseSelectListItemsSelectListItems
        {
            get { return new SelectList(DiseasesList, "DiseasesId", "Name"); }
        }
        //public IEnumerable<SelectListItem> DismanagementliSelectListItems
        //{

        //    get { return new SelectList(DiseasesManagements, "DiseasesManagementId", "ManagementProcess"); }
        //}

      
        public IEnumerable<SelectListItem> DiseasescInvestigationSelectListItems
        {
            get { return new SelectList(DiseasesInvestigations, " DiseasesInvestigationId", "Name"); }

        }
        public IEnumerable<SelectListItem> DiseasesclinicalFeatureseSelectListItems
        {
            get { return new SelectList(DisesesClinicalFeatures, "ClinicalFeatureId", "Symptom"); }
        }
    }
}

Project/DEBTALMIS/DENTALMIS.Web/Controllers/DiseasesManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DENTALMIS.Model;
using DENTALMIS.Web.Models.DiseasesSectionViewModel;

namespace DENTALMIS.Web.Controllers
{
    public class DiseasesManagementController : BaseController
    {
        //
        // GET: /DiseasesManagement/
        public ActionResult Index(DiseasesManagementViewModel model)
        {
            ModelState.Clear();
            var totalrecords = 0;
            model.ManagementProcess = model.SearchByManagementName;
            model.DiseasesList = DiseasesManager.GetAllDiseases();
            model.DisesesClinicalFeatures = DiseasesClinicalFeatureManager.GetAllFeature();
            model.DiseasesInvestigations = DiseasesInvestigationManager.GetAllInvestigation();
            model.DiseasesManagements = DiseasesManagementManager.GetAllManagementByPaging(out totalrecords, model);
            model.TotalRecords = totalrecords;

            return View(model);
        }
        public ActionResult Edit(DiseasesManagementViewModel model)
        {
            ModelState.Clear();
            model.DiseasesList = DiseasesManager.GetAllDiseases();
            model.DisesesClinicalFeatures = DiseasesClinicalFeatureManager.GetAllFeature();
            model.DiseasesInvestigations = DiseasesInvestigationManager.GetAllInvestigation();
            if (model.DiseasesManagementId > 0)
            {
                var diseaseManagement = DiseasesManagementManager.GetDeasesManagementById(model.DiseasesManagementId) ?? new DiseasesManagement();
                model.DiseasesManagementId = diseaseManagement.DiseasesManagementId;
                model.ManagementProcess = diseaseManagement.ManagementProcess;
                model.Prognosis = diseaseManagement.Prognosis;
                model.DiseasesId = diseaseManagement.DiseasesId;
                model.ClinicalFeatureId = diseaseManagement.ClinicalFeatureId;
                model.DiseasesInvestigationId = diseaseManagement.DiseasesInvestigationId;


            }
            return View(model);
        }

        public JsonResult Save(DiseasesManagementViewModel model)
        {
            int saveIndex = 0;

            var _diseaseManagement = new DiseasesManagement();
            _diseaseManagement.DiseasesId = model.DiseasesId;
            _diseaseManagement.ManagementProcess = model.ManagementProcess;
            _diseaseManagement.Prognosis = model.Prognosis;
            _diseaseManagement.DiseasesManagementId = model.DiseasesManagementId;
            _diseaseManagement.ClinicalFeatureId = model.ClinicalFeatureId;
            _diseaseManagement.DiseasesInvestigationId = model.DiseasesInvestigationId;
            
           

            saveIndex = model.DiseasesManagementId == 0 ? DiseasesManagementManager.Save(_diseaseManagement) : DiseasesManagementManager.Edit(_diseaseManagement);


            return Reload(saveIndex);
        }

        public JsonResult Delete(DiseasesManagementViewModel model)
        {
            int deleteIndex = 0;
            try
            {
                deleteIndex = DiseasesManagementManager.Delete(model.DiseasesManagementId);
            }
            catch (Exception exception)
            {

                throw new Exception(exception.Message);
            }
            return deleteIndex > 0 ? Reload() : ErroResult("Failed To Delete");
        }
	}
}

Project/DEBTALMIS/DENTALMIS.Web/Views/DiseasesManagement/Edit.cshtml
@using DENTALMIS.Web.Extension
@model DENTALMIS.Web.Models.DiseasesSectionViewModel.DiseasesManagementViewModel
@{
    ViewBag.Title = (Model.DiseasesManagementId > 0) ? "Edit" : "Add";
    Layout = "~/Views/Shared/_Layout.Dialog.cshtml";
}

@using (Html.BeginForm("Save", "DiseasesManagement", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.DiseasesManagementId)
    
    <table>

        <tr class="form_group">
            <td>
                @Html.LabelFor(x => x.Disease.Name)
                @Html.DropDownListFor(x => x.DiseasesId,Model.DiseaseSelectListItemsSelectListItems,"---Select Item---", new { @class = "text ui-widget-content ui-corner-all"  })
                @Html.ValidationMessageFor(x => x.Disease.Name)
            </td>
        </tr>
        <tr class="form_group">
            <td>
                @Html.LabelFor(x => x.DiseasesInvestigation.Name)
                @Html.DropDownListFor(x => x.DiseasesInvestigationId, Model.DiseasescInvestigationSelectListItems, "---Select Item---", new { @class = "text ui-widget-content ui-corner-all" })
                @Html.ValidationMessageFor(x => x.DiseasesInvestigation.Name)
            </td>
        </tr>
        <tr class="form_group">
            <td>
                @Html.LabelFor(x => x.DisesesClinicalFeature.Symptom)
                @Html.DropDownListFor(x => x.ClinicalFeatureId, Model.DiseasesclinicalFeatureseSelectListItems, "---Select Item---", new { @class = "text ui-widget-content ui-corner-all" })
                @Html.ValidationMessageFor(x => x.Disease.Name)
            </td>
        </tr>
        <tr class="form_group">
            <td>
                @Html.LabelFor(x => x.ManagementProcess)
                @Html.EditorFor(x => x.ManagementProcess, new { htmlAttributes = new { @class = "text ui-widget-content ui-corner-all" } })
                @Html.ValidationMessageFor(x => x.ManagementProcess)
            </td>
        </tr>
        <tr class="form_group">
            <td>
                @Html.LabelFor(x => x.Prognosis)
                @Html.EditorFor(x => x.Prognosis, new { htmlAttributes = new { @class = "text ui-widget-content ui-corner-all" } })
                @Html.ValidationMessageFor(x => x.Prognosis)
            </td>
        </tr>
      

        <tr class="form_group">
            <td style="float: right;">
                @Html.SaveButton()
            </td>
        </tr>
    </table>
}

Project/DEBTALMIS/DENTALMIS.Web/Views/DiseasesManagement/Index.cshtml
@using DENTALMIS.Utility
@using DENTALMIS.Web.Extension
@model DENTALMIS.Web.Models.DiseasesSectionViewModel.DiseasesManagementViewModel
@{
    ViewBag.Title = "DiseasesManagement";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 style="margin-left: 450px; font-weight: bolder;color: darkorange;">Diseases Management</h3>
<section class="search formCover" style="margin-bottom: 5px;">
    @using (Html.BeginForm("Index", "DiseasesManagement", FormMethod.Get, new { @class = "submit-allow ignore-validation" }))
    {
        <table>
            <tr>
                <td>
                    <strong>
                        @Html.LabelFor(x => x.ManagementProcess)

                    </strong>
                </td>
                <td></td>
                <td></td>

                <td>@Html.TextBoxFor(x => x.SearchByManagementName, new { @placeholder = "Search", @class = "search_TextBox" })</td>

                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>

                <td>
                    <strong>
                        @Html.LabelFor(x => x.Disease.Name)
                    </strong>
                </td>
                <td></td>

                <td></td>

                <td>
                    @Html.DropDownListFor(x => x.DiseasesId, Model.DiseaseSelectListItemsSelectListItems, "---Selecet Item---", new { @class = "search_dropdown" })
                </td>
                <td></td>
            </tr>
            <tr>

                <td>
                    <strong>
                        @Html.LabelFor(x => x.DisesesClinicalFeature.Symptom)
                    </strong>
                </td>
                <td></td>

                <td></td>

                <td>
                    @Html.DropDownListFor(x => x.ClinicalFeatureId, Model.DiseasesclinicalFeatureseSelectListItems, "---Selecet Item---", new { @class = "search_dropdown" })
                </td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>

                <td>
                    <strong>
                        @Html.LabelFor(x => x.DiseasesInvestigation.Name)
                    </strong>
                </td>
                <td></td>

                <td></td>

                <td>
                    @Html.DropDownListFor(x => x.DiseasesInvestigationId, Model.DiseasescInvestigationSelectListItems, "---Selecet Item---", new { @class = "search_dropdown" })
                </td>
                <td></td>

                <td>@Html.SearchButton()</td>
            </tr>
        </table>
    }
</section>


<section class="search formCover">
    <div class="additem">
        <div style="margin-top: 1px;">
            <p>@Html.Button("Add new", new { @class = "AjaxPopup", @action = "/DiseasesManagement/Edit/" })</p>
        </div>
        @{
            var grid = new WebGrid(canPage: true, rowsPerPage: AppConfig.PageSize, canSort: true, ajaxUpdateContainerId: "grid");
            grid.Bind(Model.DiseasesManagements, rowCount: Model.TotalRecords, autoSortAndPage: false);
            grid.Pager(WebGridPagerModes.All);
            @grid.GetHtml(htmlAttributes: new { id = "grid" },
            tableStyle: "webgrid-table webgrid",
            headerStyle: "webgrid-header",
            footerStyle: "webgrid-footer",
            alternatingRowStyle: "webgrid-alternating-row",
            selectedRowStyle: "webgrid-selected-row",
            rowStyle: "webgrid-row-style",
            firstText: "First",
            lastText: "last",
            nextText: "Next",
            mode: WebGridPagerModes.All,
            previousText: "Previous",
            columns: grid.Columns(
                     grid.Column("Disease.Name", header: "Diseases Name"),
                                       grid.Column("DisesesClinicalFeature.Symptom", header: "Diseses Symptom"),
                                       grid.Column("DiseasesInvestigation.Name", header: "Investigation Name"),

                                                grid.Column("ManagementProcess", header: "ManagementProcess Name"),
                                                                    grid.Column("Prognosis", header: "Prognosis"),
                grid.Column("Detail/Edit", format: @<text><button class="edit" action="/DiseasesManagement/Edit/?DiseasesManagementId=@item.DiseasesManagementId"></button></text>, canSort: false),
                         grid.Column("Delete",format:@<text><button class="delete" action="/DiseasesManagement/Delete/?DiseasesManagementId=@item.DiseasesManagementId"></button></text>, canSort: false)));



        }
    </div>
</section>