Project/DEBTALMIS/DENTALMIS.Web/Areas/DrugSection/Models/ViewModel/DrugdetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DENTALMIS.Model;

namespace DENTALMIS.Web.Areas.DrugSection.Models.ViewModel
{
    public class DrugdetailViewModel:DrugDetail
    {
        public DrugdetailViewModel()
        {
            DrugGenerics=new List<DrugGeneric>();
            DrugDetails=new List<DrugDetail>();
        }

        public List<DrugDetail> DrugDetails { get; set; }

        public List<DrugGeneric> DrugGenerics { get; set; }


        public IEnumerable<SelectListItem> DrugGenericSelectListItems
        {
            get { return new SelectList(DrugGenerics, "GenericId", "Name"); }
        }


       
    }
}

Project/DEBTALMIS/DENTALMIS.Web/Controllers/DrugBrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using DENTALMIS.Model;
using DENTALMIS.Web.Areas.DrugSection.Models.ViewModel;
using DENTALMIS.Web.Models.ClinicDescriptionModel;
using DENTALMIS.Web.ReportHelper;

namespace DENTALMIS.Web.Controllers
{
    public class DrugBrandController : BaseController
    {
        public ActionResult Index(DrugBrandViewModel model)
        {
            ModelState.Clear();
            model.Name = model.SeachByBrandName;
            //if (!model.IsSearch)
            //{
            //    model.IsSearch = true;
            //    return View(model);
            //}

            var totalrecords = 0;

           

           
            model.DrugGenerics = DrugGenericManager.GettAllGenericDrug();

            model.DrugBrands = DrugBrandManager.GetAllDrugBrand(out totalrecords, model);
            model.TotalRecords = totalrecords;

            return View(model);
        }


        public ActionResult Edit(DrugBrandViewModel model)
        {
            ModelState.Clear();
            model.DrugGenerics = DrugGenericManager.GettAllGenericDrug();
            if (model.BrandId > 0)
            {



                var _drugBrand = DrugBrandManager.GetBrandDrugById(model.BrandId) ?? new DrugBrand(); ;

                model.BrandId = _drugBrand.BrandId;
                model.Name = _drugBrand.Name;
                model.Preparation = _drugBrand.Preparation;
                model.GenericId = _drugBrand.GenericId;

            }
            return View(model);
        }


        public JsonResult Save(DrugBrandViewModel model)
        {
            int saveIndex = 0;

            var _drugBrand = new DrugBrand();

            _drugBrand.BrandId = model.BrandId;
            _drugBrand.Name = model.Name;
            _drugBrand.Preparation = model.Preparation;
            _drugBrand.GenericId = model.GenericId;
            saveIndex = model.BrandId == 0 ? DrugBrandManager.SaveDrugBrand(_drugBrand) : DrugBrandManager.EditDrugBrand(_drugBrand);
            //return saveIndex > 0 ? Reload(saveIndex) : ErroeMessageResult();
            return Reload(saveIndex);
        }

        public JsonResult Delete(DrugBrandViewModel model)
        {
            int deleteIndex = 0;

            try
            {
                deleteIndex = DrugBrandManager.DeleteDrugBrand(model.BrandId);
            }
            catch (Exception exception)
            {

                throw new Exception(exception.Message);
            }
            return deleteIndex > 0 ? Reload() : ErroResult("Failed to delete");
        }
        public void GetExcel(DrugBrandViewModel model)
        {
            List<DrugBrand> drugBrands = DrugBrandManager.Getdrugs();
            model.DrugBrands = drugBrands;

            const string fileName = "DrugBrands";
            var boundFields = new List<BoundField>
            {
                new BoundField(){HeaderText = @"Brand Name", DataField = "Name"},
                new BoundField(){HeaderText = @"Description", DataField = "Preparation"},
                new BoundField(){HeaderText = @"Generic Name", DataField = "DrugGeneric.Name"}
            };
            ReportConverter.CustomGridView(boundFields, model.DrugBrands, fileName);
        }

        public ActionResult Print(DrugBrandViewModel model)
        {
            var totalrecords = 0;
            //List<DrugBrand> drugBrands = DrugBrandManager.GetdrugBySearchKey(model.SeachByBrandName);

            List<DrugBrand> drugBrands = DrugBrandManager.Getdrugs();
            //List<DrugBrand> drugBrands = DrugBrandManager.GetAllDrugBrand(out totalrecords, model);
            model.DrugBrands = drugBrands;
            return View("_DrugBrandtPdfReport", model);
        }

     
	}
}

Project/DEBTALMIS/DENTALMIS.Web/Controllers/DrugDetailsController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DENTALMIS.BLL.Manager.DrugSectionManager;
using DENTALMIS.Model;
using DENTALMIS.Web.Areas.DrugSection.Models.ViewModel;

namespace DENTALMIS.Web.Controllers
{
    public class DrugDetailsController : BaseController
    {

        public ActionResult Index(DrugdetailViewModel model)
        {
            ModelState.Clear();
            var totalrecords = 0;
            model.DrugGenerics = DrugGenericManager.GettAllGenericDrug();
            model.DrugDetails = DrugDetailManager.GetAllDrugDetails(out totalrecords, model);
            model.TotalRecords = totalrecords;
            return View(model);





        }

        public ActionResult Edit(DrugdetailViewModel model)
        {
            ModelState.Clear();

            model.DrugGenerics = DrugGenericManager.GettAllGenericDrug();
            if (model.DrugDetailId>0)
            {
                var _drugDetails = DrugDetailManager.GetDrugDeatilsbyId(model.DrugDetailId) ?? new DrugDetail();

                model.DrugDetailId = _drugDetails.DrugDetailId;
                model.Indication = _drugDetails.Indication;
                model.Dosage = _drugDetails.Dosage;

                model.Contraindication = _drugDetails.Contraindication;
                model.SideEffect = _drugDetails.SideEffect;
                model.UseInPregnency = _drugDetails.UseInPregnency;
                model.UseInLactation = _drugDetails.UseInLactation;
                model.DrugInteraction = _drugDetails.DrugInteraction;
                model.Precaution = _drugDetails.DrugInteraction;
                model.Mechanism = _drugDetails.Mechanism;
                model.GenericId = _drugDetails.GenericId;
            }
            return View(model);
        }

        public JsonResult Save(DrugdetailViewModel model)
        {
            int saveIndex = 0;

            var _drugDetails = new DrugDetail();

            _drugDetails.DrugDetailId = model.DrugDetailId;
            _drugDetails.Indication = model.Indication;
            _drugDetails.Dosage = model.Dosage;

            _drugDetails.Contraindication = model.Contraindication;
            _drugDetails.SideEffect = model.SideEffect;
            _drugDetails.UseInPregnency = model.UseInPregnency;
            _drugDetails.UseInLactation = model.UseInLactation;
            _drugDetails.DrugInteraction = model.DrugInteraction;
            _drugDetails.Precaution = model.Precaution;
            _drugDetails.Mechanism = model.Mechanism;
            _drugDetails.GenericId = model.GenericId;

            saveIndex = model.DrugDetailId == 0 ? DrugDetailManager.SaveDrugDetail(_drugDetails) : DrugDetailManager.EditDrugdetail(_drugDetails);
            return Reload(saveIndex);

        }
        public JsonResult Delete(DrugdetailViewModel model)
        {
            int deleteIndex = 0;

            try
            {
                deleteIndex = DrugDetailManager.DeletedrugDetail(model.DrugDetailId);
            }
            catch (Exception exception)
            {

                throw new Exception(exception.Message);
            }
            return deleteIndex > 0 ? Reload() : ErroResult("Failed To Delete");
        }
    }
}

Project/DEBTALMIS/DENTALMIS.Web/Views/DrugDetails/Edit.cshtml
@using DENTALMIS.Web.Extension
@model DENTALMIS.Web.Areas.DrugSection.Models.ViewModel.DrugdetailViewModel
@{
    ViewBag.Title = (Model.DrugDetailId > 0) ? "Edit" : "Save";
    Layout = "~/Views/Shared/_Layout.Dialog.cshtml";

}
@using (Html.BeginForm("Save", "DrugDetails", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x=>x.DrugDetailId)
    @*@Html.ValidationSummary(true)*@
    <table>
        <tr class="form_group">
            <td>
                @Html.LabelFor(x => x.Indication)
                @Html.EditorFor(x => x.Indication, new { htmlAttributes = new { @class = "text ui-widget-content ui-corner-all" } })

                @Html.ValidationMessageFor(x => x.Indication)
            </td>
            <td></td>
            <td></td>

            <td></td>

            <td></td>

            <td></td>

            <td>
                @Html.LabelFor(x => x.Dosage)
                @Html.EditorFor(x => x.Dosage, new { htmlAttributes = new { @class = "text ui-widget-content ui-corner-all" } })

                @Html.ValidationMessageFor(x => x.Dosage)


            </td>
        </tr>
        <tr class="form_group">
          
            <td>
                @Html.LabelFor(x=>x.Contraindication)
                @Html.EditorFor(x=>x.Contraindication ,new{htmlattributes=new {@class="text ui-widget-content ui-corner-all"}})
                @Html.ValidationMessageFor(x=>x.Contraindication)
            </td>  
            <td></td>
            <td></td>

            <td></td>

            <td></td>

            <td></td>
            <td>
                @Html.LabelFor(x=>x.SideEffect)
                @Html.EditorFor(x=>x.SideEffect , new{ htmlAttributes=new {@class="text ui-widget-content ui-corner-all"}} )
                @Html.ValidationMessageFor(x=>x.SideEffect)
            </td>

        </tr>
        <tr class="form_group">
            <td>
                @Html.LabelFor(x => x.UseInPregnency)
                @Html.EditorFor(x => x.UseInPregnency, new { htmlAttributes = new { @class = "text ui-widget-content ui-corner-all" } })

                @Html.ValidationMessageFor(x => x.UseInPregnency)
            </td>
            <td></td>
            <td></td>

            <td></td>

            <td></td>

            <td></td>

            <td>
                @Html.LabelFor(x => x.UseInLactation)
                @Html.EditorFor(x => x.UseInLactation, new { htmlAttributes = new { @class = "text ui-widget-content ui-corner-all" } })

                @Html.ValidationMessageFor(x => x.UseInLactation)


            </td>
        </tr>
        <tr class="form_group">

            <td>
                @Html.LabelFor(x => x.DrugInteraction)
                @Html.EditorFor(x => x.DrugInteraction, new { htmlattributes = new { @class = "text ui-widget-content ui-corner-all" } })
                @Html.ValidationMessageFor(x => x.DrugInteraction)
            </td>
            <td></td>
            <td></td>

            <td></td>

            <td></td>

            <td></td>
            <td>
                @Html.LabelFor(x => x.Precaution)
                @Html.EditorFor(x => x.Precaution, new { htmlAttributes = new { @class = "text ui-widget-content ui-corner-all" } })
                @Html.ValidationMessageFor(x => x.Precaution)
            </td>

        </tr>
        <tr class="form_group">

            <td>
                @Html.LabelFor(x => x.Mechanism)
                @Html.EditorFor(x => x.Mechanism, new { htmlattributes = new { @class = "text ui-widget-content ui-corner-all" } })
                @Html.ValidationMessageFor(x => x.Mechanism)
            </td>
            <td></td>
            <td></td>

            <td></td>

            <td></td>

            <td></td>
            <td>
                @Html.LabelFor(x => x.DrugGeneric.Name)
                @Html.DropDownListFor(x => x.GenericId,Model.DrugGenericSelectListItems,"--All",  new { @class = "text ui-widget-content ui-corner-all" })
                @Html.ValidationMessageFor(x => x.DrugGeneric.Name)
            </td>

        </tr>

        <tr >
            <td class="form_group" style="float: right;">
                @Html.SaveButton()
            </td>
        </tr>
    </table>
}

Project/DEBTALMIS/DENTALMIS.Web/Views/DrugDetails/Index.cshtml
@using DENTALMIS.Utility
@using DENTALMIS.Web
@using DENTALMIS.Utility
@using DENTALMIS.Web.Extension
@model DENTALMIS.Web.Areas.DrugSection.Models.ViewModel.DrugdetailViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3 style="margin-left:450px; font-weight: bolder; color:darkorange;">Detail Description of Drug</h3>
<section class="search formCover" style="margin-bottom: 5px;">
    @using (Html.BeginForm("Index", "DrugDetails", FormMethod.Get, new { @class = "submit-allow ignore-validation" }))
    {

        <table>
            <tr>

                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    @Html.LabelFor(x => x.DrugGeneric.Name)
                </td>
                <td>
                    @Html.DropDownListFor(m => m.GenericId, Model.DrugGenericSelectListItems, "---All", new { @class = "search_dropdown" })
                </td>
                <td>
                    @Html.SearchButton()
                </td>
            </tr>
            @*<tr>
                    <td>
                        @Html.ActionLink("Add User", "Edit", "DrugBrand", new { @class = "AjaxPopup", title = "Add", @action = "DrugBrand/Edit" })
                    </td>
                </tr>*@
        </table>
    }
</section>
<section class="search formCover">
    <div class="additem">
        <div style="margin-top: 1px;">
            <p>
                @Html.Button("Add New", new { @class = "AjaxPopup", @action = "/DrugDetails/Edit/" })
            </p>
        </div>
        @{
            var grid = new WebGrid(canPage: true, rowsPerPage: AppConfig.PageSize, canSort: true, ajaxUpdateContainerId: "grid");
            grid.Bind(Model.DrugDetails, rowCount: Model.TotalRecords, autoSortAndPage: false);
            grid.Pager(WebGridPagerModes.All);
            @grid.GetHtml(htmlAttributes: new { id = "grid" },
                tableStyle: "webgrid-table webgrid",
                headerStyle: "webgrid-header",
                footerStyle: "webgrid-footer",
                alternatingRowStyle: "webgrid-alternating-row",
                selectedRowStyle: "webgrid-selected-row",
                rowStyle: "webgrid-row-style",
                firstText: "First",
                lastText: "Last",
                nextText: "Next",
                mode: WebGridPagerModes.All,
                previousText: "Previous",
                columns: grid.Columns(
                            grid.Column("DrugGeneric.Name", header: "Generic Name"),
                       grid.Column("Indication", header: "Indication"),
                                grid.Column("Dosage", header: "Dosage"),
                                grid.Column("Contraindication", header: "Contraindication"),
                                         grid.Column("SideEffect", header: "SideEffect"),
                                                  grid.Column("UseInPregnency", header: "UseInPregnency"),
                                                           grid.Column("UseInLactation", header: "UseInLactation"),
                                                                    grid.Column("DrugInteraction", header: "DrugInteraction"),
                                                                             grid.Column("Precaution", header: "Precaution"),
                                                                                      grid.Column("Mechanism", header: "Mechanism"),



                       grid.Column("Detail/Edit", format: @<text><button class="edit" action="/DrugDetails/Edit?DrugDetailId=@item.DrugDetailId"></button></text>, canSort: false),
                       grid.Column("Delete",format:@<text><button class="delete" action="/DrugDetails/Delete?DrugDetailId=@item.DrugDetailId"></button></text>, canSort: false)));
        }
    </div>
</section>