Project/DEBTALMIS/DENTALMIS.Web/Controllers/ClinicAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DENTALMIS.Model;
using DENTALMIS.Web.Models.ClinicDescriptionModel;

namespace DENTALMIS.Web.Controllers
{
    public class ClinicAccountController : BaseController
    {
        //
        // GET: /ClinicAccount/
        public ActionResult Index(ClinicAcountViewModel model)
        {
            ModelState.Clear();
            var totalrecords = 0;



            model.ClinicAccounts = ClinicAccountManager.GetAllAccountByPaging(out totalrecords, model).Where(x => (x.Date >= model.FromDate || model.FromDate == null) && (x.Date <= model.ToDate || model.ToDate == null)).ToList(); ;



            model.TotalRecords = totalrecords;

            return View(model);

        }



        public ActionResult Edit(ClinicAcountViewModel model)
        {
            ClinicAccount clinicAccount = ClinicAccountManager.GetAccountiesById(model.ClinicAccountId);
            if (model.ClinicAccountId > 0)
            {


                model.ClinicAccountId = clinicAccount.ClinicAccountId;
                model.Income = clinicAccount.Income;
                model.OutCome = clinicAccount.OutCome;
                model.Date = clinicAccount.Date;
                model.DayTotalIncome = clinicAccount.DayTotalIncome;
                model.TotalIncome = clinicAccount.TotalIncome;




            }


            return View(model);
        }

        public List<ClinicAccount> GetAllATotalIncomeById()
        {
            List<ClinicAccount> totalIncomes = ClinicAccountManager.GetAllATotalIncomeById();

            return totalIncomes;
        }

        public JsonResult Save(ClinicAcountViewModel model)
        {


            int saveIndex = 0;



            ClinicAccount clinicAccount = new ClinicAccount();
            clinicAccount.ClinicAccountId = model.ClinicAccountId;
            clinicAccount.Income = model.Income;
            clinicAccount.OutCome = model.OutCome;
            clinicAccount.Date = model.Date;
            clinicAccount.DayTotalIncome = clinicAccount.Income - clinicAccount.OutCome;
            clinicAccount.TotalIncome = clinicAccount.DayTotalIncome;


            List<ClinicAccount> allATotalIncomeById = GetAllATotalIncomeById();

            foreach (ClinicAccount account in allATotalIncomeById)
            {

                clinicAccount.TotalIncome += account.DayTotalIncome;


            }
            saveIndex = model.ClinicAccountId == 0 ? ClinicAccountManager.Save(clinicAccount) : ClinicAccountManager.Edit(clinicAccount); ;

            return Reload(saveIndex);
        }
        public JsonResult Delete(ClinicAcountViewModel model)
        {
            int deleteIndex = 0;
            try
            {
                deleteIndex = ClinicAccountManager.Delete(model.ClinicAccountId);
            }
            catch (Exception exception)
            {

                throw new Exception(exception.Message);
            }
            return deleteIndex > 0 ? Reload() : ErroResult("Failed To Delete");
        }
    }
}

Project/DEBTALMIS/DENTALMIS.Web/Views/ClinicAccount/Edit.cshtml
@using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder
@using DENTALMIS.Web.Extension
@model DENTALMIS.Web.Models.ClinicDescriptionModel.ClinicAcountViewModel
           @{
    ViewBag.Title = (Model.ClinicAccountId > 0) ? "Edit" : "Save";
    Layout = "~/Views/Shared/_Layout.Dialog.cshtml";

}
@using (Html.BeginForm("Save", "ClinicAccount", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.ClinicAccountId)

    <table>
        <tr class="form_group">
            <td>
                @Html.LabelFor(x => x.Income)
                @Html.EditorFor(x => x.Income, new { htmlAttributes = new { @class = "text ui-widget-content ui-corner-all" } })

                @Html.ValidationMessageFor(x => x.Income)
            </td>
            <td></td>
            <td></td>

            <td></td>

            <td></td>

            <td></td>


            <td>
                @Html.LabelFor(x => x.OutCome)
                @Html.EditorFor(x => x.OutCome, new { htmlAttributes = new { @class = "text ui-widget-content ui-corner-all" } })

                @Html.ValidationMessageFor(x => x.OutCome)
            </td>
            <td></td>
            <td></td>

            <td></td>

            <td></td>

            <td></td>

            <td>
                @Html.LabelFor(x => x.Date)
                @Html.EditorFor(x => x.Date, new { htmlAttributes = new { @class = "text ui-widget-content ui-corner-all" } })

                @Html.ValidationMessageFor(x => x.Date)
            </td>

        </tr>
        <tr class="form_group">





          
            <td style="float: left">
                @Html.SaveButton()
            </td>






        </tr>

       


    </table>
}

Project/DEBTALMIS/DENTALMIS.Web/Views/ClinicAccount/Index.cshtml
@using DENTALMIS.Utility
@using DENTALMIS.Web.Extension
@model DENTALMIS.Web.Models.ClinicDescriptionModel.ClinicAcountViewModel
@{
    ViewBag.Title = "Clinic Accessoriess";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 style="margin-left: 450px; font-weight: bolder;color: darkblue;">[--Clinic Account--]</h3>
<section class="search formCover" style="margin-bottom: 5px;">
    @using (Html.BeginForm("Index", "ClinicAccount", FormMethod.Get, new { @class = "submit-allow ignore-validation" }))
    {
        <table>
            <tr>
                <td>
                    <strong>
                        @Html.LabelFor(x => x.FromDate)

                    </strong>
                </td>
                <td></td>
                <td></td>

                <td>@Html.EditorFor(x => x.FromDate, new { htmlAttributes = new { @placeholder = "From date", @class = "search_TextBox" } })</td>

                <td></td>
                <td>
                    <strong>
                        @Html.LabelFor(x => x.ToDate)

                    </strong>
                </td>
                <td></td>
                <td></td>

                <td>@Html.EditorFor(x => x.ToDate, new { htmlAttributes = new { @placeholder = "From date", @class = "search_TextBox" } })</td>

                <td></td>




                <td>@Html.SearchButton()</td>
            </tr>
        </table>
    }
</section>


<section class="search formCover">
    <div class="additem">
        <div style="margin-top: 1px;">
            <p>@Html.Button("Add new", new { @class = "AjaxPopup", @action = "/ClinicAccount/Edit/" })</p>
        </div>
        @{
            var grid = new WebGrid(canPage: true, rowsPerPage: AppConfig.PageSize, canSort: true, ajaxUpdateContainerId: "grid");
            grid.Bind(Model.ClinicAccounts, rowCount: Model.TotalRecords, autoSortAndPage: false);
            grid.Pager(WebGridPagerModes.All);
            @grid.GetHtml(htmlAttributes: new { id = "grid" },
            tableStyle: "webgrid-table webgrid",
            headerStyle: "webgrid-header",
            footerStyle: "webgrid-footer",
            alternatingRowStyle: "webgrid-alternating-row",
            selectedRowStyle: "webgrid-selected-row",
            rowStyle: "webgrid-row-style",
            firstText: "First",
            lastText: "last",
            nextText: "Next",
            mode: WebGridPagerModes.All,
            previousText: "Previous",
            columns: grid.Columns(
                                                grid.Column("Income", header: "Clinic Income In Taka"),

                                                                                                                              

                                       grid.Column("OutCome", header: "OutCome In Taka "),

                                                           grid.Column("Date", header: "  Date", format: @<text>@(item.Date == null ? "" : item.Date.ToString("dd/MM/yyyy"))</text>),



                                                                                                                                                                                                                                                                                                                    grid.Column("DayTotalIncome", header: "Day Total Income In Taka" ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            grid.Column("TotalIncome", header: "Total Income In Taka"),



                grid.Column("Detail/Edit", format: @<text><button class="edit" action="/ClinicAccount/Edit/?ClinicAccountId=@item.ClinicAccountId"></button></text>, canSort: false),
                         grid.Column("Delete",format:@<text><button class="delete" action="/ClinicAccount/Delete/?ClinicAccountId=@item.ClinicAccountId"></button></text>, canSort: false)));



        }
    </div>
</section>